trigger:
  branches:
    include:
    - master
    - idt-develop
    - idt-feature-LC-*
    - idt-release-v*
    - idt-hotfix-v*
  tags:
    include:
      - '*'

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.3'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm test
  
  - task: Docker@2
    inputs:
      containerRegistry: 'lpgregistry ACR'
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
        repository: 'lpg-management/prod'
      ${{ else }}:
        repository: 'lpg-management/test'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: '$(Build.SourceBranchName)'